### ISSUE TITLE
Selection of data file under explorer's "Files" tab produces web error

### ISSUE THREAD

**Issue by bzkrouse** [RhoInc/codebook#18] opened 2018-07-09 17:36 UTC
![codebook_issue2](https://user-images.githubusercontent.com/14199771/42466458-febeeef0-837c-11e8-86e1-6a767fc00820.PNG)

**Comment by jwildfire** [comment] 2018-07-10 04:10
@bzkrouse What branch (or SHA) should I use to recreate the error and debug?

**Comment by jwildfire** [comment] 2018-07-10 14:31
Definitely seeing the same error. Looks like all of the files are being marked as "selected" (hence they are all formatted in blue) for some reason. Since the [web-only demo](https://rawgit.com/RhoInc/web-codebook/master/build/test-page/explorer.html) works ok, my best guess is that this is caused by a problem with the R settings object, but I'll dig in more later today or tomorrow and try to debug.

**Comment by jwildfire** [comment] 2018-07-11 13:33
Updating webcharts to the latest release (v1.10.0) fixes the issue. The problem was caused by some changes in the webcharts `table` data flow introduced in v1.7 or v1.8 - we were still using v1.6.1 here.

Note that a the minor bug where all of the rows of the table are highlighted is still present. That's unrelated to the core problem that caused the app to bomb, and will require a bug fix release in web-codebook. I've filed an [issue](https://github.com/RhoInc/web-codebook/issues/274) and will get that fix in ASAP.

**Closed** 2018-07-13 17:30 UTC
Labels: bug
